### ISSUE TITLE
Grunt task

### ISSUE THREAD

**Issue by Grawl** [uipoet/webfonts#7]
It will be super awesome to have this package as a Grunt task.

Now I use this just like any other binary with console but think that it possible to use it with [grunt-exec](https://www.npmjs.org/package/grunt-exec) or similar Grunt plugin.

**Comment by uipoet** [comment]
Should be easy enough to call webfonts from Grunt or any other of the many build systems out there without having to create a dependency on them inside the library, itself.

**Comment by sapegin** [comment]
Why not use [grunt-webfont](https://github.com/sapegin/grunt-webfont)?

**Comment by Grawl** [comment]
@sapegin `grunt-webfont` is for “Generate custom icon webfonts from SVG files via Grunt.” But I think that “web-oriented font” is not an icons. Is a letters. Classical definition of this term. And I want to convert classic, not iconic fonts from one format to another.

**Comment by jimmyandrade** [comment]
Hi @Grawl — chiming in on a closed thread because I wanted the same thing (running font generation from a build without a bespoke plugin). Since `webfonts` is unmaintained now, a Grunt task here is unlikely to happen.

Full disclosure: I help maintain a pure-JS alternative, [`webfont`](https://github.com/itgalaxy/webfont) (no `s`), which you can drive from any build system without a dedicated plugin — as a CLI (via `grunt-shell` / an npm script) or via its Node API:

```js
const { webfont } = require("webfont");

grunt.registerTask("webfont", function () {
  const done = this.async();
  webfont({ files: "fonts/*.ttf", formats: ["woff2", "woff"] })
    .then((result) => {
      // grunt.file.write the buffers in `result` (result.woff2, result.woff, ...)
      done();
    })
    .catch(done);
});
```

If your goal was specifically icon fonts from SVGs, `grunt-webfont` (mentioned above) is another option. Would either cover your case? Happy to help wire it up.

**Comment by Grawl** [comment]
It's a surprise to see this “hello from 2014”
